### ISSUE TITLE
Tests and CI

### ISSUE THREAD

**Issue by LeSasse** [juaml/nimgen#6]
There are no tests as of yet. I want to add at least a few basic unit tests. Not sure how easy this will be, in particular the AHBA infrastructure, but at least basic functions should be tested. I will try for now to bring coverage to something like 60 to 70% and add some basic CI infrastructure using pytest, tox and github actions.

**Comment by fraimondo** [comment]
Check here: https://github.com/juaml/junifer/tree/dev

`tox.ini`
`pyproject.toml`
`.github/workflows/ci.yml`
`.github/workflows/lint.yml`

@synchon moved the repo to use tox for that

**Comment by synchon** [comment]
@LeSasse I can help after the junifer hackathon, if you need any 🦾

**Comment by LeSasse** [comment]
CI has been set up. Thanks @fraimondo and @synchon !

Tests are missing for the following modules:
* nimgen/expressions.py
* nimgen/nimgen.py
* nimgen/pipelines/*
* nimgen/smash.py
* nimgen/utils.py
* nimgen/web.py
